apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
    version: v1
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        name: {{.Values.name}}
        app: {{.Values.name}}
    spec:
      hostNetwork: true
      containers:
        - name: {{.Values.name}}
          securityContext:
            privileged: true
          image: {{.Values.image}}
          imagePullPolicy: Always
          command: ["sh", "-c", "/run.sh"]
          env:
            - name: SLEEP_INTERVAL
              value: "30"
          resources:
            requests:
              cpu: 5m
              memory: 10Mi
          volumeMounts:
            - mountPath: /cfg
              name: cfg
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: "{{.Values.imagePullSecrets}}"
{{- end }}
      volumes:
        - name: cfg
          configMap:
            name: {{.Values.name}}
